name: Build and Publish on release published

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        # The name of the image you would like to push
        name: vetermanve/damn
        # The login username for the registry
        username: vetermanve
        # The login password for the registry
        password: ${{secrets.DOCKER_AUTH_TOKEN}}
        tags: "latest, ${{ steps.get_version.outputs.VERSION }}"
